// Code generated by protoc-gen-gorums. DO NOT EDIT.

package protocol

import (
	context "context"
	gorums "github.com/relab/gorums"
	encoding "google.golang.org/grpc/encoding"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	sync "sync"
)

// A Configuration represents a static set of nodes on which quorum remote
// procedure calls may be invoked.
type Configuration struct {
	gorums.Configuration
	qspec QuorumSpec
}

// Nodes returns a slice of each available node. IDs are returned in the same
// order as they were provided in the creation of the Manager.
func (c *Configuration) Nodes() []*Node {
	gorumsNodes := c.Configuration.Nodes()
	nodes := make([]*Node, 0, len(gorumsNodes))
	for _, n := range gorumsNodes {
		nodes = append(nodes, &Node{n})
	}
	return nodes
}

func init() {
	if encoding.GetCodec(gorums.ContentSubtype) == nil {
		encoding.RegisterCodec(gorums.NewCodec())
	}
}

// Manager maintains a connection pool of nodes on
// which quorum calls can be performed.
type Manager struct {
	*gorums.Manager
}

// NewManager returns a new Manager for managing connection to nodes added
// to the manager. This function accepts manager options used to configure
// various aspects of the manager.
func NewManager(opts ...gorums.ManagerOption) (mgr *Manager) {
	mgr = &Manager{}
	mgr.Manager = gorums.NewManager(opts...)
	return mgr
}

// NewConfiguration returns a configuration based on the provided list of nodes.
// Nodes can be supplied using WithNodeMap or WithNodeList or WithNodeIDs.
func (m *Manager) NewConfiguration(qspec QuorumSpec, opts ...gorums.ConfigOption) (c *Configuration, err error) {
	c = &Configuration{
		qspec: qspec,
	}
	c.Configuration, err = gorums.NewConfiguration(m.Manager, opts...)
	if err != nil {
		return nil, err
	}
	return c, nil
}

// Nodes returns a slice of available nodes on this manager.
// IDs are returned in the order they were added at creation of the manager.
func (m *Manager) Nodes() []*Node {
	gorumsNodes := m.Manager.Nodes()
	nodes := make([]*Node, 0, len(gorumsNodes))
	for _, n := range gorumsNodes {
		nodes = append(nodes, &Node{n})
	}
	return nodes
}

type Node struct {
	*gorums.Node
}

// asynchronous call to all replicas which returns a fully signed certificate as soon as a threshold of replicas responds
func (c *Configuration) GetCertificate(ctx context.Context, in *Request) *AsyncReply {
	cd := gorums.QuorumCallData{
		Message: in,
		Method:  "protocol.Certification.GetCertificate",
	}
	cd.QuorumFunction = func(req protoreflect.ProtoMessage, replies map[uint32]protoreflect.ProtoMessage) (protoreflect.ProtoMessage, bool) {
		r := make(map[uint32]*Reply, len(replies))
		for k, v := range replies {
			r[k] = v.(*Reply)
		}
		return c.qspec.GetCertificateQF(req.(*Request), r)
	}

	fut := c.Configuration.AsyncCall(ctx, cd)
	return &AsyncReply{fut}
}

// QuorumSpec is the interface of quorum functions for Certification.
type QuorumSpec interface {

	// GetCertificateQF is the quorum function for the GetCertificate
	// asynchronous quorum call method. The in parameter is the request object
	// supplied to the GetCertificate method at call time, and may or may not
	// be used by the quorum function. If the in parameter is not needed
	// you should implement your quorum function with '_ *Request'.
	GetCertificateQF(in *Request, replies map[uint32]*Reply) (*Reply, bool)
}

// Certification is the server-side API for the Certification Service
type Certification interface {
	GetCertificate(context.Context, *Request, func(*Reply, error))
}

func RegisterCertificationServer(srv *gorums.Server, impl Certification) {
	srv.RegisterHandler("protocol.Certification.GetCertificate", func(ctx context.Context, in *gorums.Message, finished chan<- *gorums.Message) {
		req := in.Message.(*Request)
		once := new(sync.Once)
		f := func(resp *Reply, err error) {
			once.Do(func() {
				finished <- gorums.WrapMessage(in.Metadata, resp, err)
			})
		}
		impl.GetCertificate(ctx, req, f)
	})
}

type internalReply struct {
	nid   uint32
	reply *Reply
	err   error
}

// AsyncReply is a async object for processing replies.
type AsyncReply struct {
	*gorums.Async
}

// Get returns the reply and any error associated with the called method.
// The method blocks until a reply or error is available.
func (f *AsyncReply) Get() (*Reply, error) {
	resp, err := f.Async.Get()
	if err != nil {
		return nil, err
	}
	return resp.(*Reply), err
}
